# -*- coding: utf-8 -*-
"""inference.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vDi7IDpAvFZ4VVpDOb5dSEctkbNYh-dR
"""

import streamlit as st
from loan_model import LoanApprovalModel

# Load model
model = LoanApprovalModel('model.pkl')

# Judul
st.title("📊 Prediksi Persetujuan Pinjaman")
st.write("Masukkan data pemohon untuk memprediksi apakah pinjaman akan **disetujui** atau **ditolak**.")

# Form input pengguna
with st.form("loan_form"):
    person_age = st.number_input("Umur Pemohon", min_value=18, max_value=100, value=30)
    person_gender = st.selectbox("Jenis Kelamin", ['Male', 'Female'])
    person_education = st.selectbox("Pendidikan Terakhir", ['High School', 'Bachelor', 'Master', 'PhD', 'Other'])
    person_income = st.number_input("Pendapatan Tahunan", min_value=1000, value=45000)
    person_emp_exp = st.number_input("Lama Pengalaman Kerja (Tahun)", min_value=0, max_value=40, value=5)
    person_home_ownership = st.selectbox("Status Kepemilikan Rumah", ['Rent', 'Own', 'Mortgage', 'Other'])
    loan_amnt = st.number_input("Jumlah Pinjaman", min_value=1000, value=10000)
    loan_intent = st.selectbox("Tujuan Pinjaman", [
        'debt_consolidation', 'home_improvement', 'credit_card',
        'major_purchase', 'medical', 'venture'
    ])
    loan_int_rate = st.number_input("Tingkat Suku Bunga (%)", min_value=0.0, value=12.5)
    loan_percent_income = st.number_input("Persentase Pendapatan untuk Pinjaman", min_value=0.0, value=0.22)
    cb_person_cred_hist_length = st.number_input("Lama Riwayat Kredit (Tahun)", min_value=1, value=3)
    credit_score = st.number_input("Skor Kredit", min_value=300, max_value=850, value=680)
    previous_loan_defaults_on_file = st.selectbox("Ada Pinjaman Bermasalah Sebelumnya?", ['Yes', 'No'])

    submit = st.form_submit_button("Prediksi Pinjaman")

# Proses prediksi
if submit:
    input_data = {
        'person_age': person_age,
        'person_gender': person_gender,
        'person_education': person_education,
        'person_income': person_income,
        'person_emp_exp': person_emp_exp,
        'person_home_ownership': person_home_ownership,
        'loan_amnt': loan_amnt,
        'loan_intent': loan_intent,
        'loan_int_rate': loan_int_rate,
        'loan_percent_income': loan_percent_income,
        'cb_person_cred_hist_length': cb_person_cred_hist_length,
        'credit_score': credit_score,
        'previous_loan_defaults_on_file': previous_loan_defaults_on_file
    }

    try:
        result = model.predict(input_data)
        st.success(f"Hasil Prediksi: **{result}**")
    except ValueError as e:
        st.error(f"Terjadi kesalahan dalam input: {e}")

