# -*- coding: utf-8 -*-
"""NO3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10o6mydmeF1aEYp8lBWohIDfZvqlIcGYH
"""

import pickle
import pandas as pd

# 1. Load model dan encoder
with open('model.pkl', 'rb') as f:
    data = pickle.load(f)
    model = data['model']
    encoder_dict = data['encoders']

# 2. Data input untuk inference (data baru yang akan diprediksi)
new_data = {
    'person_age': 30,
    'person_gender': 'Male',
    'person_education': 'Master',
    'person_income': 45000,
    'person_emp_exp': 5,
    'person_home_ownership': 'OWN',
    'loan_amnt': 10000,
    'loan_intent': 'PERSONAL',
    'loan_int_rate': 10.5,
    'loan_percent_income': 0.22,
    'cb_person_cred_hist_length': 3,
    'credit_score': 680,
    'previous_loan_defaults_on_file': 'No'
}

# 3. Preprocessing (encode) data input
df_new = pd.DataFrame([new_data])
for col in encoder_dict:
    if col in df_new.columns:
        df_new[col] = encoder_dict[col].transform(df_new[col])

# 4. Melakukan prediksi
result = model.predict(df_new)[0]

# 5. Menampilkan hasil prediksi
status = 'Disetujui' if result == 1 else 'Ditolak'
print(f"Status Pinjaman: {status}")

