# -*- coding: utf-8 -*-
"""NO2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Z-KJRFVqMDuKlqZtMMkMxj2QnDkyaENl
"""

# -*- coding: utf-8 -*-
"""loan_inference_model.py

Automatically generated for loan prediction model inference.
"""

import pickle
import pandas as pd

class LoanApprovalModel:
    def __init__(self, model_path='model.pkl'):
        with open(model_path, 'rb') as f:
            data = pickle.load(f)
            self.model = data['model']
            self.encoders = data['encoders']

    def preprocess(self, input_data: dict):
        df = pd.DataFrame([input_data])

        for col, encoder in self.encoders.items():
            if col in df.columns:
                try:
                    df[col] = encoder.transform(df[col])
                except ValueError as e:
                    raise ValueError(f"Value '{df[col].iloc[0]}' tidak ditemukan pada encoder kolom '{col}'. "
                                     f"Pastikan nilai input sesuai dengan data training.") from e
        return df

    def predict(self, input_data: dict):
        df = self.preprocess(input_data)
        prediction = self.model.predict(df)[0]
        return 'Disetujui' if prediction == 1 else 'Ditolak'

